version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    labels:
      - "dependencies"
      - "javascript"
    open-pull-requests-limit: 5

  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    labels:
      - "dependencies"
      - "javascript"
    open-pull-requests-limit: 5

  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 5
